### ISSUE TITLE
can't open .moc3

### ISSUE THREAD

**Issue by wister1A** [Perfare/AzurLaneLive2DExtract#1]
this error show on logs when i try to open .moc3 with Cubism 3 Viewer(for OC), what did i do wrong?

[1;31mERROR [m[1m[ Exception in thread "AWT-EventQueue-0" net.arnx.jsonic.JSONException: fails to convert {Version=3, FileReferences={Moc=huonululu_3.moc3, Textures=[textures/texture_00.png], Motions=[motions/mission.motion3.json, motions/mail.motion3.json, motions/touch_special.motion3.json, motions/main_1.motion3.json, motions/main_3.motion3.json, motions/touch_head.motion3.json, motions/home.motion3.json, motions/idle.motion3.json, motions/login.motion3.json, motions/wedding.motion3.json, motions/complete.motion3.json, motions/touch_body.motion3.json, motions/main_2.motion3.json, motions/mission_complete.motion3.json], Physics=huonululu_3.physics3.json}, Groups=[{Target=Parameter, Name=LipSync, Ids=[ParamMouthOpenY]}, {Target=Parameter, Name=EyeBlink, Ids=[ParamEyeLOpen, ParamEyeROpen]}]} to class com.live2d.cubism.doc.model.exporter.bv$d: $.FileReferences.Motions[0][0] ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON$Context.convertInternal(JSON.java:1775) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON.parse(JSON.java:1182) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON.parse(JSON.java:1170) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON.decode(JSON.java:707) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.model.exporter.bv$h.a(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.a.b$a.a(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.OWViewerDropFrame.openModel3Json(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.OWViewerDropFrame.openMoc(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.OWViewerDropFrame.openFile(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.OWViewerDropFrame.access$openFile(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.U.a(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.U.invoke(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.util.W.c(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.OWViewerDropFrame.openAs(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.OWViewerDropFrame.access$openAs(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.J.a(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.cubism.doc.modeling.ui.viewerForOriginalWorkflow.J.invoke(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.ui.control.d.a(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.ui.control.d.invoke(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.ui.menu.CMenuItem.doAction_exe(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at com.live2d.ui.control.c.actionPerformed(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at javax.swing.AbstractButton.doClick(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Component.processMouseEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at javax.swing.JComponent.processMouseEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Component.processEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Container.processEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Component.dispatchEventImpl(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Container.dispatchEventImpl(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Component.dispatchEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Container.dispatchEventImpl(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Window.dispatchEventImpl(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.Component.dispatchEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventQueue.access$500(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventQueue$3.run(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventQueue$3.run(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.security.AccessController.doPrivileged(Native Method) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventQueue$4.run(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventQueue$4.run(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.security.AccessController.doPrivileged(Native Method) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventQueue.dispatchEvent(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at java.awt.EventDispatchThread.run(Unknown Source) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[ Caused by: java.lang.UnsupportedOperationException: Cannot convert class java.lang.String to class com.live2d.cubism.doc.model.exporter.bv$g ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.ObjectConverter.convert(Converter.java:1676) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON.postparse(JSON.java:1310) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON$Context.postparseInternal(JSON.java:1754) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.CollectionConverter.convert(Converter.java:1472) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON.postparse(JSON.java:1310) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON$Context.postparseInternal(JSON.java:1754) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.MapConverter.convert(Converter.java:1589) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON.postparse(JSON.java:1310) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON$Context.postparseInternal(JSON.java:1754) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.ObjectConverter.convert(Converter.java:1650) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON.postparse(JSON.java:1310) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON$Context.postparseInternal(JSON.java:1754) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.ObjectConverter.convert(Converter.java:1650) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON.postparse(JSON.java:1310) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   at net.arnx.jsonic.JSON$Context.convertInternal(JSON.java:1762) ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m
[1;31mERROR [m[1m[   ... 58 more ][m [1;31mat jp.noids.ui.c.f$a (f$a.kt:-1) write()[m

**Comment by Perfare** [comment]
duplicate #2 , I'll fix it later.
