### ISSUE TITLE
[BUG] Model3Json不符合规范以及Motion中片段数量

### ISSUE THREAD

**Issue by df32** [Perfare/AzurLaneLive2DExtract#2]
model3.json不符合规范
---------
model3.json中，按照[Cubism 3](https://github.com/Live2D/CubismSpecs)规范，Motions的值必须为对象而非数组。
一些浏览程序并不支持数组。
```js
{
  "Version": 3,
  "FileReferences": {
    "Moc": "banrenma_2.moc3",
    "Textures": [
      "textures/texture_00.png"
    ],
    "Motions": {
		"Idle": [
			  {"File":"motions/idle.motion3.json"},
			  {"File":"motions/home.motion3.json"},
			  {"File":"motions/main_1.motion3.json"}
			],
		"TapBody": [
			  {"File":"motions/touch_body.motion3.json"},
			  {"File":"motions/touch_special.motion3.json" },
			  {"File":"motions/touch_head.motion3.json"},
			  {"File":"motions/main_2.motion3.json"}
			]
    },
    "Physics": "banrenma_2.physics3.json"
  },
//...
```
motion3.json中片段节点没有计算
-----
程序代码生成motion3.json时没有计算TotalSegmentCount和TotalPointCount的值。
每条Curve由Segment和Point组成。
![每条Curve由Segment和Point组成](http://docs.live2d.com/wp-content/uploads/2018/05/grapheditor_value.png)
Segment有4种：线性曲线（Linear=0）、贝赛尔曲线（Bezier=1）、阶梯曲线（Stepped=2）、反向阶梯曲线（InverseStepped=3）。
``` js
      "Segments": [
        0,		//点(0,1)
        1,
        0,		//线性曲线
        1,		//点(1,0)
        0,
        0,		//线性曲线
        4.8,		//点(4.8,1)
        1
      ]
```
参考[CubismMotionSegmentType](https://github.com/Live2D/CubismWebSamples/blob/develop/Framework/motion/cubismmotioninternal.ts#L35)和[CubismMotion::parse()](https://github.com/Live2D/CubismWebSamples/blob/develop/Framework/motion/cubismmotion.ts#L629)，计算方式如下
```Csharp
	totalPointCount = 0;
	totalSegmentCount = 0;

	foreach (var curve in curves)
	{
		for (var segmentPosition = 0; segmentPosition < curve.Segments.Count; )
		{
			if (segmentPosition == 0)
			{
				totalPointCount += 1;
				segmentPosition += 2;
			}

			var segment = (int)curve.Segments[segmentPosition];
			switch (segment)
			{
				//case Linear: 
				case 0:
					totalPointCount += 1;
					segmentPosition += 3;
					break;
				//case Bezier: 
				case 1:
					totalPointCount += 3;
					segmentPosition += 7;
					break;
				//case Stepped: 
				case 2:
					totalPointCount += 1;
					segmentPosition += 3;
					break;
				//case InverseStepped: 
				case 3:
					totalPointCount += 1;
					segmentPosition += 3;
					break;
				default:
					throw new Exception($"Unknown segment type of the curve.");
			}

			totalSegmentCount++;
		}
	}
```

生成的motion3.json中全都为线性曲线
-----
如上所说，segment包含多种类型。而程序生成的segment都是线性曲线。
错误示例
![提尔比茨的灵异易拉罐](https://user-images.githubusercontent.com/9204710/47221300-93c68580-d3e6-11e8-85cb-7352bf058999.gif)

**Comment by UlyssesWu** [comment]
*（Off Topic）*
感觉楼主对L2D颇为了解，请问除了这些公开Spec外，楼主对于moc3格式是否有所研究？

**Comment by Perfare** [comment]
前面两个问题已经解决了，重点是第三个问题。
关于4种Segment，其中Stepped有明显的特征，所以我已经单独处理了，解决了易拉罐的问题。
剩下的三种Segment，Unity的StreamedClip在存储时会计算出Hermite系数进行存储，原谅我这数学渣完全不懂怎么把这Hermite系数转为Bezier曲线，所以现在用的最土的方法就是每两个点的曲线中取20个点，测试了一下基本没有问题，缺点就是导致motion3文件非常大。。。
可能需要个大佬拯救一下

**Comment by Perfare** [comment]
花了点时间复习了一下相关数学知识，终于把四种Segment都实现了
但是一些细节上还是有点问题，感觉把每帧都算出来进行重采样可能是更好的做法（
