### ISSUE TITLE
[Request] Motion's UserData restoration

### ISSUE THREAD

**Issue by yukariin** [Perfare/AzurLaneLive2DExtract#4]
Current implementation is [hardcoded](https://github.com/Perfare/AzurLaneLive2DExtract/blob/master/AzurLaneLive2DExtract/Program.cs#L85) to UserDataCount=0 and TotalUserDataSize=0.
But according to Unity SDK it [converts](https://github.com/Live2D/CubismUnityComponents/blob/master/Assets/Live2D/Cubism/Framework/Json/CubismMotion3Json.cs#L242) motion's user data to AnimationEvent related to motion's AnimationClip. Where event's time is UD time and stringParameter is value.
In Azur Lane's L2D setup all motions except idle has an animation even that calls OnFinishAnim with motion id as arg. Which runs idle animation by default.

**Comment by Perfare** [comment]
AnimationEvent has been implemented and has improved a lot of other things.
