### ISSUE TITLE
Latest Live2D Can't be extract

### ISSUE THREAD

**Issue by Sakura95561** [Perfare/AzurLaneLive2DExtract#5]
**Azur Lane got a Update and i Can't Extract the files anymore.
older files works just fine.**

```
ハンドルされていない例外: SevenZip.DataErrorException: Data Error
   場所 SevenZip.Compression.LZMA.Decoder.Code(Stream inStream, Stream outStream, Int64 inSize, Int64 outSize, ICodeProgress progress)
   場所 AssetStudioCore.SevenZipHelper.StreamDecompress(Stream inStream, Stream outStream, Int64 inSize, Int64 outSize)
   場所 AssetStudioCore.BundleFile.ReadFormat6(EndianBinaryReader bundleReader, Boolean padding)
   場所 AssetStudioCore.BundleFile..ctor(String path, EndianBinaryReader bundleReader)
   場所 AzurLaneLive2DExtract.Program.Main(String[] args)
```

**Comment by yukariin** [comment]
Works fine for me for both CN and JP updated files. Could you upload the file?

**Comment by Sakura95561** [comment]
https://drive.google.com/open?id=10k-JUPJNmYtUo13IxicMAZbZktpkfgx_

**Comment by yukariin** [comment]
Where from these files?

**Comment by Sakura95561** [comment]
direct from my phone

**Comment by yukariin** [comment]
I mean CN/JP/KR/EN.

**Comment by Sakura95561** [comment]
jp

**Comment by yukariin** [comment]
Welp, looks like your files broken. Check your files md5 sum with one from hashes-live2d.csv

**Comment by Sakura95561** [comment]
oh ... you are right. the files are broken. i have copy the files again and now its works. 
weird that has never happened to me before. Thank you for your help
