### ISSUE TITLE
Ark Royal Live2D Issues

### ISSUE THREAD

**Issue by TwinDragon** [Perfare/AzurLaneLive2DExtract#6]
I only tested Ark Royal's Live2D, so this may or may not affect others. I'm using the EN client currently, and when you extract the Live2D and use a program such as Live2DViewerEX on Steam to edit and check the motions, there are a few where her arm will disappear during the motion or something. This happened on Yukariin's fork. Perfare's version, during the login animation, one of her legs would be completely off center.

I've seen something similar to this before when I was originally working on these models, like Atago for instance. Sometimes her animations wouldn't properly work because of the decryption not working fully, but once I got new files from a friend of mine with an updated program, it worked fine afterwards. If need be, I can upload the decrypted asset for Ark Royal to poke around with.

**Comment by Perfare** [comment]
Upload the file to me, I will check this error.

**Comment by TwinDragon** [comment]
I prefixed both archives from which extractor was used as both had differing issues with the model. This may not be the only error, but if you'd like, I can upload all of the extracted L2D models from your source if need be.
[Perfare_huangjiafangzhou_3.zip](https://github.com/Perfare/AzurLaneLive2DExtract/files/3487997/Perfare_huangjiafangzhou_3.zip)
[Yukariin_huangjiafangzhou_3.zip](https://github.com/Perfare/AzurLaneLive2DExtract/files/3487998/Yukariin_huangjiafangzhou_3.zip)

The devs are constantly changing things in the L2D models, probably to thwart the decryption of the assets.

**Comment by Perfare** [comment]
Open with the official Cubism3Viewer, I don't think there is anything wrong.
![gif](https://user-images.githubusercontent.com/12952226/62810973-8673b680-bb32-11e9-9b77-d10e87b7c4d8.gif)

**Comment by TwinDragon** [comment]
It ends up being a problem with https://store.steampowered.com/app/616720/Live2DViewerEX/ though. Which I would assume is using the same Cubism3 SDK. I don't have a GIF atm of the bug I'm experiencing to show, but can get one later if necessary.

**Comment by Perfare** [comment]
This issue is a problem with Live2DViewerEX, you should contact the developer of Live2DViewerEX.

**Comment by TwinDragon** [comment]
Guess I can try, they're not very helpful though.. But thanks anyway for at least looking.
