### ISSUE TITLE
图层显示不正常

### ISSUE THREAD

**Issue by libaibaba** [Perfare/AzurLaneLive2DExtract#7]
大佬，我尝试使用您的软件解少女咖啡枪，结果在Cubism3Viewer打开是这样的![7F54$LXG0{~2UXSQ%OA$@11](https://user-images.githubusercontent.com/52236285/67217260-008bba00-f457-11e9-83f4-62266b7d70d9.jpg)
使用了Cubism3SDK后在unity里是这样的
![7QRVJ}R42~FIF O BU$5491](https://user-images.githubusercontent.com/52236285/67217264-01bce700-f457-11e9-8efc-855f7d6c332d.png)

更有甚者是直接让Cubism3Viewer崩溃的，请问这是Cubism3的原因吗
[l2d01.zip](https://github.com/Perfare/AzurLaneLive2DExtract/files/3751507/l2d01.zip)
fu'sha附上文件
![J }ZC66XODGCK74HE UQL5N](https://user-images.githubusercontent.com/52236285/67217470-595b5280-f457-11e9-9cfa-377d2f673fa6.jpg)

**Comment by Perfare** [comment]
moc文件有简单的加密，晚点会在博客上发布提取工具
![txnb](https://user-images.githubusercontent.com/12952226/67275742-d4734600-f4f5-11e9-9973-ef7097f8102c.gif)

**Comment by libaibaba** [comment]
大佬强啊，平时AssetStudio也受你的照顾了
